### ISSUE TITLE
다중 쿼리 처리

### ISSUE THREAD

**Issue by lazyduo** [smartmind-team/thanosql-magic#1]
한 Cell에 semi-colon으로 구분해서 쿼리가 이어질 경우 처리가 불가한 이슈가 있습니다.

방법1. Magic에서 split으로 끊어서 끊어진 쿼리 수 만큼 API Call?

방법2. Engine에서 Parser가 처리?

**Comment by inwookie** [comment]
SQL query를 돌릴때 semi-colon을 사용한다는거 자체가 이 query는 여기까지가 하나의 완성된 query로 보는 것 이기 때문에 방법 1 이 더 적합하다고 생각합니다.

**Comment by lazyduo** [comment]
@inwookie @jyoon0808 @Indoo-Park 

semicolon 구분해서 하나씩 API 콜하는거 처리는 했는데,

display되는 거랑 마지막에 df로 받을 수 있는거는 오직 *마지막 쿼리문*인 문제가 있는데

좋은 해결 방안 있을까요. or 마지막만 받거나 볼 수 있는거로 하고 끝낸다.

example)

```
%%thanosql
SELECT * FROM users;
SELECT * FROM model;
```

위 쿼리 같은경우 SELECT * FROM model만 보여짐.

**Comment by lazyduo** [comment]
@inwookie @jyoon0808 @Indoo-Park 

semicolon 구분해서 하나씩 API 콜하는거 처리는 했는데,

display되는 거랑 마지막에 df로 받을 수 있는거는 오직 *마지막 쿼리문*인 문제가 있는데

좋은 해결 방안 있을까요. or 마지막만 받거나 볼 수 있는거로 하고 끝낸다.

example)

```
%%thanosql
SELECT * FROM users;
SELECT * FROM model;
```

위 쿼리 같은경우 SELECT * FROM model만 보여짐.

**Comment by jyoon0808** [comment]
제 생각에는 파이썬 같은 경우에
```python
a, b = 1,2
a
b
```
이런식으로 식행 시켰을 때 마지막 b만 프린트돼서 나오듯이 저희도 마지막 쿼리만 받아볼 수 있게 해도 괜찮을 것 같아요.

**Comment by lazyduo** [comment]
네 이대로 merge 할게요
